set_property -dict {PACKAGE_PIN V2 IOSTANDARD LVCMOS33} [get_ports {reset}]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports clk]
#Setare led-uri cu result
set_property PACKAGE_PIN G1 [get_ports result[0]]
set_property IOSTANDARD LVCMOS33 [get_ports result[0]]
set_property PACKAGE_PIN G2 [get_ports result[1]]
set_property IOSTANDARD LVCMOS33 [get_ports result[1]]
set_property PACKAGE_PIN F1 [get_ports result[2]]
set_property IOSTANDARD LVCMOS33 [get_ports result[2]]
set_property PACKAGE_PIN F2 [get_ports result[3]]
set_property IOSTANDARD LVCMOS33 [get_ports result[3]]
set_property PACKAGE_PIN E1 [get_ports result[4]]
set_property IOSTANDARD LVCMOS33 [get_ports result[4]]
set_property PACKAGE_PIN E2 [get_ports result[5]]
set_property IOSTANDARD LVCMOS33 [get_ports result[5]]
set_property PACKAGE_PIN E3 [get_ports result[6]]
set_property IOSTANDARD LVCMOS33 [get_ports result[6]]
set_property PACKAGE_PIN E5 [get_ports result[7]]
set_property IOSTANDARD LVCMOS33 [get_ports result[7]]
set_property PACKAGE_PIN E6 [get_ports result[8]]
set_property IOSTANDARD LVCMOS33 [get_ports result[8]]
set_property PACKAGE_PIN C3 [get_ports result[9]]
set_property IOSTANDARD LVCMOS33 [get_ports result[9]]
set_property PACKAGE_PIN B2 [get_ports result[10]]
set_property IOSTANDARD LVCMOS33 [get_ports result[10]]
set_property PACKAGE_PIN A2 [get_ports result[11]]
set_property IOSTANDARD LVCMOS33 [get_ports result[11]]
set_property PACKAGE_PIN B3 [get_ports result[12]]
set_property IOSTANDARD LVCMOS33 [get_ports result[12]]
set_property PACKAGE_PIN A3 [get_ports result[13]]
set_property IOSTANDARD LVCMOS33 [get_ports result[13]]
set_property PACKAGE_PIN B4 [get_ports result[14]]
set_property IOSTANDARD LVCMOS33 [get_ports result[14]]
set_property PACKAGE_PIN A4 [get_ports result[15]]
set_property IOSTANDARD LVCMOS33 [get_ports result[15]]